tesis.pdf :: 2_y_3_qubits.tex     fudamentos_teoricos.tex  ruskai.tex agradecimientos.tex  introduccion.tex         simbolos.tex c_y_r.tex            objetivos.tex            tesis.tex dedicatoria.tex      operaciones_PCE.tex
-include ~/makefile
